recurrent:
  architecture: "many to one rnn" # "deep rnn", "bidirectional rnn", "one to many rnn", "many to one rnn", "many to many rnn"
  cell_type: "rnn"
  architectures:
    deep_rnn:
      output_size: 10
      skip_connections: False
      hidden_size: 512
      stack_number: 1

    bidirectional:
      output_size: 10
      skip_connections: False
      hidden_size: 512
      stack_number: 3

    onetomany:
      output_size: 10
      hidden_size: 512
      stack_number: 1

    manytoone:
      output_size: 10
      hidden_size: 512
      stack_number: 1

    manytomany:
      output_size: 10
      hidden_size: 512
      stack_number: 1

  cell:
    rnn:
      input_size: 784
      hidden_size: 512
      bias: True
      param_dtype: jnp.float32
      activation_fn: tanh

    lstm:
      input_size: 784
      hidden_size: 512
      bias: True
      param_dtype: jnp.float32
      gate_fn: sigmoid
      activation_fn: tanh

    gru:
      input_size: 784
      hidden_size: 512
      bias: True
      param_dtype: jnp.float32
      gate_fn: sigmoid
      activation_fn: tanh

    hippo:
      input_size: 784
      hidden_size: 512
      bias: True
      param_dtype: jnp.float32
      gate_fn: sigmoid
      activation_fn: tanh
      measure: "legs"
      lambda_n: 1.0
      fourier_type: "fru"
      alpha: 0.0
      beta: 1.0
      GBT_alpha: 0.5
      rnn_cell: LSTMCell # LSTMCell, GRUCell
