state_spaces:
  transition_matrix:
    n: 10 # int
    GBT_alpha: 0.5 # float
    measure: "legs" # str
    lambda_n: 1.0
    fourier_type: "fru"
    alpha: 0.0
    beta: 1.0

  HiPPO:
    n: 10 # int
    GBT_alpha: 0.5 # float
    measure: "legs" # str

  S4:
    param_1:
    param_2:
    param_3:
