# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
files: ^src/|^examples/
default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/python-poetry/poetry
    rev: "1.2.0b3" # add version here
    hooks:
      - id: poetry-lock
      - id: poetry-check
      - id: poetry-export
        args: ["--dev", "-f", "requirements.txt", "-o", "requirements.txt"]
        verbose: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
