[tool.poetry]
name = "s4mer"
version = "0.1.0"
license = "GPL-3.0-or-later"
description = "Repo for the testing and developing of state space models, transformers and the hybrid between the two; trained on whole slide digital pathology image data."
authors = [
    "Bryan Gass <bryank123@live.com>",
    ]
maintainers = [
    "Bryan Gass <bryank123@live.com>",
]
readme = "README.md"
repository = "https://github.com/Dana-Farber-AIOS/s4mer"
classifiers = [
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Framework :: Sphinx",
    "Framework :: Pytest",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Image Processing",
    "Topic :: Scientific/Engineering :: Image Recognition",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
    "Topic :: Software Development :: Libraries :: Python Modules",
]


[tool.poetry.dependencies]
python = ">=3.9,<3.11"
scipy = { version = "^1.8.1" }
jax = { version = "^0.3.14", extras = ["cpu"] }
black = { version = "^22.6.0" }
flax = { version = "^0.5.2" }
optax = { version = "^0.1.3" }
numpy = { version = "^1.23.1" }
notebook = { version = "^6.4.12" }
torch = { url = "https://download.pytorch.org/whl/nightly/cpu/torch-1.13.0.dev20220616-cp39-none-macosx_11_0_arm64.whl" }
torchvision = { url = "https://download.pytorch.org/whl/nightly/cpu/torchvision-0.14.0.dev20220616-cp39-cp39-macosx_11_0_arm64.whl" }
torchaudio = { url = "https://download.pytorch.org/whl/nightly/cpu/torchaudio-0.14.0.dev20220603-cp39-cp39-macosx_11_0_arm64.whl" }
jupyter = "^1.0.0"
ipykernel = "^6.15.1"
ipython = "^8.4.0"
pre-commit = "^2.20.0"

[tool.poetry.dev-dependencies]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
