models:
  model_type: "rnn"
  hippo:
    n: 10 # int
    GBT_alpha: 0.5 # float
    measure: legs # str
    lambda_n: 1.0
    fourier_type: "fru"
    alpha: 0.0
    beta: 1.0
  deep_rnn:
    output_size: 10
    skip_connections: False
    hidden_size: 256
    stack_number: 3
  cells:
    cell_type: "rnn" # rnn, lstm, gru, legs_lstm, legt_lstm, lmu_lstm, lagt_lstm, fru_lstm, fout_lstm, foud_lstm, legs_gru, legt_gru, lmu_gru, lagt_gru, fru_gru, fout_gru, foud_gru
    rnn:
      input_size: 28 * 28
      hidden_size: 256
      bias: True
      param_dtype: jnp.float32
      activation_fn: tanh
    gated_rnn:
      input_size: 28 * 28
      hidden_size: 256
      bias: True
      param_dtype: jnp.float32
      gate_fn: sigmoid
      activation_fn: tanh
    hippo:
      input_size: 28 * 28
      hidden_size: 256
      bias: True
      param_dtype: jnp.float32
      gate_fn: sigmoid
      activation_fn: tanh
      measure: "legs"
      lambda_n: 1.0
      fourier_type: "fru"
      alpha: 0.0
      beta: 1.0
      GBT_alpha: 0.5
      rnn_cell: LSTMCell # LSTMCell, GRUCell
  s4:
    param_1:
    param_2:
    param_3:
  lstm:
    param_1:
    param_2:
    param_3:

training:
  seed: 1701
  key_num: 10
  num_epochs: 25
  weight_decay: 0.0005
  lr: 0.00003
  batch_size: 64
  input_length: 5#
