name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: Lint Code In src
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Vanilla Black Lint
        uses: psf/black@stable
        with:
          src: "./src/"
