name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Vanilla Black Lint
      #   uses: psf/black@stable
      #   with:
      #     src: "./src/"
      - name: Wemake Python Style Guide
        uses: wemake-services/wemake-python-styleguide@0.16.1
