name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: We make Python Style Guide
        uses: wemake-services/wemake-python-styleguide@0.16.1
        continue-on-error: true
        with:
          reporter: "github-pr-review"
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
